FROM apache/airflow:slim-2.10.5-python3.11

# Cài đặt Java
USER root
RUN apt-get update && \
    apt-get install -y gcc python3-dev openjdk-17-jdk && \
    apt-get clean

#Set JAVA home
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow
# Tải thư viện cần thiết
COPY requirements.txt .
RUN pip install  --no-cache-dir --quiet -r requirements.txt
