FROM jupyter/base-notebook:python-3.11

# Thiết lập thư mục làm việc
WORKDIR /home/jovyan/work

# Cài đặt Java
USER root
RUN apt-get update && \
    apt-get install -y gcc python3-dev openjdk-17-jdk && \
    apt-get clean

#Set JAVA home
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH


# Tải thư viện cần thiết
COPY requirements.txt .
RUN pip install  --no-cache-dir --quiet -r requirements.txt

